import {wordDefinitions,actionDefinitions,insightFor} from './word-insights.js';
import {glossaryExpansion} from './pastoral.js';
export {pastoralConcepts as concepts} from './pastoral.js';
const readingVocabulary=[
 ['Covenant',['covenant','covenants'],'A relationship established by God in which he makes promises and calls his people to respond to him. In this study, follow the promises to David and the language of mercy towards Abraham and his descendants.',1],
 ['House',['house','houses'],'This word can mean a building, a household or a family line. In 2 Samuel 7, the movement between a house for God and the house God will establish for David is important to the passage.',1],
 ['King',['king','kings'],'A ruler who governs a people. The study asks what kind of King the world needs, and how the promised Son of David differs from rulers whose power and faithfulness do not last.',1],
 ['Kingdom',['kingdom','kingdoms'],'The rule of a king and the people or realm under that rule. Gabriel says that the kingdom of Mary’s son will have no end, drawing the story back to God’s promise to David.',6],
 ['Throne',['throne','thrones'],'The seat of a ruler, which can also stand for royal authority. A lasting throne is a promise of lasting rule, rather than a claim about how long a piece of furniture will survive.',1],
 ['David',['david'],'The king of Israel to whom God promises a lasting house and throne. Luke identifies Joseph with David’s house and connects Jesus with the throne of his ancestor David.',1],
 ['Peace',['peace'],'More than the absence of conflict, biblical peace includes the well-being that comes under God’s good rule. Notice how the promised ruler, the shepherd and the announcement of Jesus’ birth bring this hope together.',2],
 ['Justice',['justice'],'Giving what is right and establishing a life together that reflects God’s righteous rule. Isaiah connects the promised ruler with justice that will endure.',2],
 ['Righteousness',['righteousness','righteous'],'Being right before God and living in a way that honours him. Read each occurrence in context: it may describe God’s rule, a person’s life or the relationship God establishes with his people.',2],
 ['Bethlehem',['bethlehem'],'David’s town and the small place named in the promise of a coming ruler. In Luke, it becomes the setting for Jesus’ birth when Joseph travels there with Mary.',3],
 ['Shepherd',['shepherd','shepherds'],'Someone who cares for a flock. The image also describes the care and leadership of a ruler, while the shepherds near Bethlehem are the people who first hear the angelic announcement.',3],
 ['Servant',['servant','servants','handmaid'],'A person who serves another. Pay attention to who is called a servant in each passage, because the word can refer to David, the figure in Isaiah’s prophecy or someone responding to God in faith.',4],
 ['Salvation',['salvation'],'God’s work of rescuing and restoring. The passages connect salvation with forgiveness, deliverance and the hope of God’s people, and they show that God’s purpose reaches the nations.',4],
 ['Nations',['nation','nations','gentiles'],'The peoples beyond Israel, as well as the peoples of the world more broadly. Isaiah’s promise and Simeon’s words show that God’s salvation is never meant to remain within one small community.',4],
 ['Light',['light'],'A picture of hope, revelation and salvation in these passages. Follow how light answers darkness in Isaiah and how Simeon describes Jesus as a light for the Gentiles.',2],
 ['Holy Spirit',['holy spirit'],'God’s Spirit, who is active in the announcements, recognition and public revelation of Jesus. Notice what the Spirit does in each scene instead of treating every mention as an isolated theme.',5],
 ['Mercy',['mercy','mercies'],'God’s compassionate faithfulness towards people in need. Mary’s song connects his mercy to those who fear him and to the promises he made to Abraham and his descendants.',7],
 ['Humble',['humble','lowly','lowliness'],'Those who are brought low or do not stand in a position of worldly importance. Mary’s song contrasts God’s care for the lowly with his response to the proud and powerful.',7],
 ['Saviour',['savior','saviors'],'One who rescues. The WEB uses the spelling “Savior”; the angel’s announcement applies this title to Jesus and connects his birth with good news for the people.',9],
 ['Christ',['christ'],'A title meaning “Anointed One”, closely related to “Messiah”. It identifies Jesus with God’s promised deliverer; it is not a second personal name.',9],
 ['Lord',['lord','lords'],'A title of authority whose meaning depends on the context. In the birth announcement it helps identify who Jesus is. The WEB uses “Yahweh” for God’s personal name in the Old Testament.',9],
 ['Yahweh',['yahweh'],'God’s personal name as printed in the World English Bible Old Testament. Many other English Bibles represent this name with “LORD” in capital letters.',1],
 ['Son',['son','sons'],'A word of family relationship. These readings connect the promised king with David’s family and lead us to Jesus’ unique relationship with his Father; the meaning must be read in each setting.',6],
 ['Repentance',['repentance','repent'],'Turning away from sin towards God. John calls people to bear fruit that fits repentance, which means that a response to God should become visible in the way they live.',12],
 ['Baptism',['baptism','baptize','baptized','baptizing'],'An immersion or washing with water. Luke 3 describes John’s baptism and the baptism of Jesus; read the purpose and events of each carefully rather than assuming every detail is the same.',12],
 ['Witness',['witness','witnesses'],'Someone who tells what they have seen or know. Act I prepares for the wider Luke–Acts journey, in which the good news about Jesus will be carried to the nations.',10]
].map(([word,forms,definition,week])=>({word,forms,definition:glossaryExpansion.find(g=>g.word===word)?.definition||definition,week}));
export const glossary=glossaryExpansion.map(g=>({...g,forms:readingVocabulary.find(v=>v.word===g.word)?.forms||[]})).sort((a,b)=>a.word.localeCompare(b.word));
const stop=new Set('a an the and or but if so as at by for from in into of off on onto out over to up upon with without through about after before between under than that this these those there here then when where why how who whom whose which what while he she it they them him her his hers its their theirs we us our ours you your yours i me my mine myself himself herself themselves yourselves itself is are was were be been being am will shall would should may might can could must do does did doing have has had having not no nor all any each every either neither both some such many much more most very also just now again already still only once other another own same even ever never away back down again one two three first because until among against yet let oh says said say saying came come went go behold therefore yes truly indeed'.split(' '));
export const actionGroups=[['Come',['come','comes','came','coming']],['Give',['give','gives','given','gave','giving']],['Say',['say','says','said','saying']],['See',['see','sees','saw','seen','seeing']],['Hear',['hear','hears','heard','hearing']],['Go',['go','goes','went','gone','going']],['Bring',['bring','brings','brought','bringing']],['Know',['know','knows','knew','known','knowing']],['Bless',['bless','blesses','blessed','blessing']],['Make',['make','makes','made','making']],['Call',['call','calls','called','calling']],['Speak',['speak','speaks','spoke','spoken','speaking']],['Return',['return','returns','returned','returning']],['Rejoice',['rejoice','rejoices','rejoiced','rejoicing']],['Believe',['believe','believes','believed','believing']],['Fear',['fear','fears','feared','fearing']],['Save',['save','saves','saved','saving']],['Serve',['serve','serves','served','serving']]].map(([word,forms])=>({word,forms,definition:actionDefinitions[word]}));
export function tokens(text){return (text.toLowerCase().replace(/[’']/g,"'").match(/[a-z]+(?:'[a-z]+)?/g)||[]).map(t=>t.replace(/'s$/,''));}
export function countForms(text,forms){const ts=tokens(text);return forms.reduce((total,form)=>{const fs=tokens(form);let n=0;for(let i=0;i<=ts.length-fs.length;i++)if(fs.every((f,j)=>ts[i+j]===f))n++;return total+n;},0);}
export function analyze(verses,category='keywords'){
 let candidates=category==='actions'?actionGroups:readingVocabulary;
 if(category!=='actions'){
  const known=new Set(readingVocabulary.flatMap(g=>g.forms));const raw=new Set(verses.flatMap(v=>tokens(v.text)));
  candidates=[...readingVocabulary,...[...raw].filter(w=>!stop.has(w)&&!known.has(w)&&w.length>2).map(w=>({word:w[0].toUpperCase()+w.slice(1),forms:[w],definition:wordDefinitions[w[0].toUpperCase()+w.slice(1)]}))];
 }
 return candidates.map(w=>{const perVerse=verses.map(v=>countForms(v.text,w.forms));return {...w,definition:insightFor(w.word,verses,w.definition),perVerse,count:perVerse.reduce((a,b)=>a+b,0)};}).filter(w=>w.count>=2).sort((a,b)=>b.count-a.count||a.word.localeCompare(b.word));
}
export function groupSessions(sessions,rhythm){return rhythm==='fortnightly'?Array.from({length:Math.ceil(sessions.length/2)},(_,i)=>sessions.slice(i*2,i*2+2)):sessions.map(s=>[s]);}
